{{- if not .Values.serviceAccount.name -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "traefik.serviceAccountName" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccountAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
