name: CI-pullrequest

on:
  pull_request:
    branches:
      - main
      - main-source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout into branch
        run: git checkout -b staging-pr-workflow

      - name: Pull scripts
        run: sudo make pull-scripts

      - name: Pull in all relevant branches
        run: git fetch origin main
      
      - name: Validate 
        run: sudo make validate
